version: "3"
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - ./screts/.env
    volumes:
      - .:/code
      - python-packages:/usr/local/lib/python3.10/site-packages
      - python-bin:/usr/local/bin
    ports:
      - "8000:8000"


  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - db-volume:/data/postgres/:/var/lib/postgresql/data

volumes:
  python-packages:
  python-bin:
  db-volume: